name: Dorafactory multisig app CICD

on:
  push:
    branches: [ main,dev ]

jobs:

  build:
    runs-on: ubuntu-18.04
    permissions:
      id-token: write
      contents: read
    steps:
    - name: Git clone the repository
      uses: actions/checkout@v1
    - name: Build image
      run: |
        docker build -t multisig-app:local -f Dockerfile .
    - name: Configure AWS Credentials
      uses: aws-actions/configure-aws-credentials@master
      with:
        role-to-assume: ${{ secrets.AWS_ROLE }}
        aws-region: ap-southeast-1
    - name: Login to Amazon ECR
      id: login-ecr
      uses: aws-actions/amazon-ecr-login@v1
    - name: Tag, push  image to Amazon ECR
      env:
        ECR_REGISTRY: ${{ steps.login-ecr.outputs.registry }}
        ECR_REPOSITORY: multisig-app
        IMAGE_TAG: ${{ github.ref_name }}
      run: |
        docker tag multisig-app:local $ECR_REGISTRY/$ECR_REPOSITORY:$IMAGE_TAG
        docker push $ECR_REGISTRY/$ECR_REPOSITORY:$IMAGE_TAG
    - name: Redeploy on aws
      run: |
        aws eks update-kubeconfig --region  ap-southeast-1 --name ${{ secrets.EKS_CLUSTER }}
        kubectl rollout restart deploy multisig-app-dev
